### ISSUE TITLE
Savon doesn't seem to support HTTPS proxy

### ISSUE THREAD

**Issue by sjmh** [savonrb/savon#418]
Attemping to use an https proxy like so:

``` ruby
#!/usr/bin/env ruby
require 'rubygems'
require 'savon'

client = Savon.client do
    wsdl "http://host.example.com/osapi/com/opsware/folder/FolderService?wsdl"
    proxy "https://user:pass@host.example.com:443"
end

client.operations
```

results in:

```
D, [2013-03-22T15:09:56.188541 #9174] DEBUG -- : HTTPI GET request to host.example.com (net_http)
/Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/http/response.rb:41:in `read_status_line': wrong status line: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">" (Net::HTTPBadResponse)
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/http.rb:1405:in `block in transport_request'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/http.rb:1402:in `catch'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/http.rb:1402:in `transport_request'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/http.rb:1375:in `request'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/httpi-2.0.2/lib/httpi/adapter/net_http.rb:33:in `block in request'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/httpi-2.0.2/lib/httpi/adapter/net_http.rb:55:in `block in do_request'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/http.rb:851:in `start'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/httpi-2.0.2/lib/httpi/adapter/net_http.rb:54:in `do_request'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/httpi-2.0.2/lib/httpi/adapter/net_http.rb:31:in `request'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/httpi-2.0.2/lib/httpi.rb:137:in `request'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/httpi-2.0.2/lib/httpi.rb:103:in `get'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/wasabi-3.0.0/lib/wasabi/resolver.rb:36:in `load_from_remote'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/wasabi-3.0.0/lib/wasabi/resolver.rb:26:in `resolve'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/wasabi-3.0.0/lib/wasabi/document.rb:113:in `xml'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/wasabi-3.0.0/lib/wasabi/document.rb:131:in `parse'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/wasabi-3.0.0/lib/wasabi/document.rb:118:in `parser'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/wasabi-3.0.0/lib/wasabi/document.rb:61:in `soap_actions'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/savon-2.1.0/lib/savon/client.rb:30:in `operations'
    from ./webservices.rb:11:in `<main>'
```

Appears that savon doesn't set the fact that the request needs to be SSL when using a SSL proxy.  Attempted to force the issue by adding an :ssl_proxy global option that set the @http_request.ssl value to true via the configure_proxy on the request - this resulted in:

```
D, [2013-03-22T15:12:41.699162 #9237] DEBUG -- : HTTPI GET request to host.example.com (net_http)
/Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/openssl/buffering.rb:174:in `read_nonblock': end of file reached (EOFError)
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/openssl/buffering.rb:174:in `sysread_nonblock'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/openssl/buffering.rb:174:in `read_nonblock'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/protocol.rb:153:in `rbuf_fill'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/http.rb:912:in `connect'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/http.rb:861:in `do_start'
    from /Users/shajducko/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/net/http.rb:850:in `start'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/httpi-2.0.2/lib/httpi/adapter/net_http.rb:54:in `do_request'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/httpi-2.0.2/lib/httpi/adapter/net_http.rb:31:in `request'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/httpi-2.0.2/lib/httpi.rb:137:in `request'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/httpi-2.0.2/lib/httpi.rb:103:in `get'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/wasabi-3.0.0/lib/wasabi/resolver.rb:36:in `load_from_remote'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/wasabi-3.0.0/lib/wasabi/resolver.rb:26:in `resolve'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/wasabi-3.0.0/lib/wasabi/document.rb:113:in `xml'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/wasabi-3.0.0/lib/wasabi/document.rb:131:in `parse'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/wasabi-3.0.0/lib/wasabi/document.rb:118:in `parser'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/wasabi-3.0.0/lib/wasabi/document.rb:61:in `soap_actions'
    from /Users/shajducko/.rvm/gems/ruby-2.0.0-p0/gems/savon-2.1.0/lib/savon/client.rb:30:in `operations'
    from ./webservices.rb:11:in `<main>'
```

**Comment by matisoffn** [comment]
Still no fix for this?
