### ISSUE TITLE
Fix failing specs

### ISSUE THREAD

**Issue by perlun** [savonrb/savon#629]
These are currently failing:

```
1) Options global: :no_message_tag includes the 'message tag' encapsulation step
     Failure/Error: expect(response.http.body.scan(/<tns:extLoginData>/).count).to eq(2)
       
       expected: 2
            got: 1
       
       (compared using ==)
     # ./spec/savon/options_spec.rb:73:in `block (3 levels) in <top (required)>'
  2) Savon knows the message tag for :vies
     Failure/Error: expect(message_tag).to eq(['urn:ec.europa.eu:taxud:vies:services:checkVat:types', 'checkVat'])
       
       expected: ["urn:ec.europa.eu:taxud:vies:services:checkVat:types", "checkVat"]
            got: ["urn:ec.europa.eu:taxud:vies:services:checkVat", "checkVatRequest"]
       
       (compared using ==)
     # ./spec/savon/features/message_tag_spec.rb:32:in `block (2 levels) in <top (required)>'
  3) Savon knows the message tag for :betfair
     Failure/Error: expect(message_tag).to eq(['http://www.betfair.com/publicapi/v5/BFExchangeService/', 'getBet'])
       
       expected: ["http://www.betfair.com/publicapi/v5/BFExchangeService/", "getBet"]
            got: ["http://www.betfair.com/publicapi/v5/BFExchangeService/", "getBetIn"]
       
       (compared using ==)
     # ./spec/savon/features/message_tag_spec.rb:27:in `block (2 levels) in <top (required)>'
Finished in 4.37 seconds
336 examples, 3 failures
Failed examples:
rspec ./spec/savon/options_spec.rb:61 # Options global: :no_message_tag includes the 'message tag' encapsulation step
rspec ./spec/savon/features/message_tag_spec.rb:30 # Savon knows the message tag for :vies
rspec ./spec/savon/features/message_tag_spec.rb:25 # Savon knows the message tag for :betfair
```

**Comment by tjarratt** [comment]
Thanks for opening this and providing the necessary incentive for me to fix up the failing specs @perlun, I really, truly appreciate it. These specs have been passing for a while, so I'm going to close this.

**Comment by perlun** [comment]
:+1:
