### ISSUE TITLE
Savon with Zuora SOAP

### ISSUE THREAD

**Issue by dmhalejr** [savonrb/savon#684]
Trying to use savon (2.11.0) with Zuora's SOAP API and seem to be having trouble when utilizing any of their operations. 

The code: (redacted for security purposes)
```
require 'savon'
require 'em-http-request'

USERNAME = ""
PASSWORD = ""

HTTPI.adapter = :net_http

# First Call to Grab sessionToken
login_client = Savon.client(wsdl: 'zuora.a.66.0_sandbox.wsdl')
login = login_client.call(:login, message: { username: "#{USERNAME}", password: "#{[PASSWORD]}" })
sessionToken = login.body[:login_response][:result][:session]

# Subsequent Calls
token_client = Savon.client(wsdl: 'zuora.a.66.0_sandbox.wsdl', headers: {session: "#{sessionToken}"}, convert_request_keys_to: 'camelcase')
token_client.call(:subscribe)
```

Error: 
```
NoMethodError: undefined method `split' for :session:Symbol
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http/header.rb:172:in `capitalize'
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http/header.rb:165:in `block in each_capitalized'
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http/header.rb:164:in `each'
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http/header.rb:164:in `each_capitalized'
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http/generic_request.rb:321:in `write_header'
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http/generic_request.rb:182:in `send_request_with_body'
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http/generic_request.rb:130:in `exec'
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:1406:in `block in transport_request'
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:1378:in `request'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/httpi-2.4.0/lib/httpi/adapter/net_http.rb:65:in `perform'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/httpi-2.4.0/lib/httpi/adapter/net_http.rb:42:in `block in request'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/httpi-2.4.0/lib/httpi/adapter/net_http.rb:78:in `call'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/httpi-2.4.0/lib/httpi/adapter/net_http.rb:78:in `block in do_request'
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/httpi-2.4.0/lib/httpi/adapter/net_http.rb:76:in `do_request'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/httpi-2.4.0/lib/httpi/adapter/net_http.rb:33:in `request'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/httpi-2.4.0/lib/httpi.rb:160:in `request'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/httpi-2.4.0/lib/httpi.rb:132:in `post'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/savon-2.11.0/lib/savon/operation.rb:94:in `block in call_with_logging'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/savon-2.11.0/lib/savon/request_logger.rb:12:in `call'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/savon-2.11.0/lib/savon/request_logger.rb:12:in `log'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/savon-2.11.0/lib/savon/operation.rb:94:in `call_with_logging'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/savon-2.11.0/lib/savon/operation.rb:54:in `call'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/savon-2.11.0/lib/savon/client.rb:36:in `call'
```

Let me know if you need any additional information from me. I'm fairly certain I'm doing something incorrect.

**Comment by tjarratt** [comment]
Hey @dmhalejr sorry to hear that you're having problems using Savon. I, too, often had a lot of problems integrating with SOAP services back when I first discovered Savon.

I don't have a lot of helpful tips, but I can recommend you try a different HTTPI adapter -- `net/http` is pretty crufty, I'd recommend HTTPClient or Curb. The stack trace you provided seems entirely unreasonable, I can't imagine there's a good reason for net/http to be raising this exception, possibly this was fixed by ruby 2.1.6 (which is the the latest stable version for 2.1 as far as I can tell).

**Comment by dmhalejr** [comment]
@tjarratt Kept running into issues on my end even after running ```curb``` and updating Ruby to the latest. 

Luckily I reached out Zuora and they were able to point me to their sample Zuora integration leveraging savon already. :relieved: 

Wish I could have figured it out myself, but this will work for my needs! 

Link: https://github.com/zuorasc/zuora

Thanks again!

**Comment by tjarratt** [comment]
I'm really delighted to hear that zuora is using Savon. Thanks for sharing that and brightening up my day, @dmhalejr.
