### ISSUE TITLE
Getting error with httpclient-2.6.0.1 Object#timeout is deprecated

### ISSUE THREAD

**Issue by henrytseng** [savonrb/savon#778]
Is anyone getting this error 

```
/Users/henry/.rvm/gems/ruby-2.3.1@caredox/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:746:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/henry/.rvm/gems/ruby-2.3.1@caredox/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:616:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/henry/.rvm/gems/ruby-2.3.1@caredox/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/henry/.rvm/gems/ruby-2.3.1@caredox/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:950:in `read_body_length': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/henry/.rvm/gems/ruby-2.3.1@caredox/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:746:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/henry/.rvm/gems/ruby-2.3.1@caredox/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:616:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/henry/.rvm/gems/ruby-2.3.1@caredox/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/henry/.rvm/gems/ruby-2.3.1@caredox/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:950:in `read_body_length': Object#timeout is deprecated, use Timeout.timeout instead.
Problem with calling, error

(soap:Receiver) Server was unable to process request. ---> Array cannot be null.
Parameter name: bytes

/Users/henry/.rvm/gems/ruby-2.3.1@caredox/gems/savon-2.11.1/lib/savon/response.rb:85:in `raise_soap_and_http_errors!'
/Users/henry/.rvm/gems/ruby-2.3.1@caredox/gems/savon-2.11.1/lib/savon/response.rb:14:in `initialize'
```

**Comment by installero** [comment]
Having the same deprecation warning

**Comment by barros3** [comment]
anyone? .. i have that problem

Login to openshift.redhat.com: mymail@mymail.com
Password: pass

/var/lib/gems/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:746:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.
/var/lib/gems/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:616:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/var/lib/gems/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/var/lib/gems/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:950:in `read_body_length': Object#timeout is deprecated, use Timeout.timeout instead.
The OpenShift Online (Next Gen) Developer Preview is here! We will not be accepting new users onto the OpenShift Online (v2) platform.
