### ISSUE TITLE
rubyntlm sideeffects when using net_http adapter

### ISSUE THREAD

**Issue by coldnebo** [savonrb/savon#819]
## problem 

When HTTPI.adapter is set to :net_http and Mechanize is used, Savon generates an error of the form:

```
ArgumentError:
       Invalid version of rubyntlm. Please use v0.3.2+.
```

This appears to be because Mechanize loads a different version of ntlm (from Gemfile.lock):
```
mechanize (2.7.5)
      ...
      ntlm-http (~> 0.1, >= 0.1.1)
      ...
```
than httpi expects (from [httpi.gemspec](https://github.com/savonrb/httpi/blob/master/httpi.gemspec)):
```
    s.add_development_dependency 'rubyntlm', '~> 0.3.2'
```

## unexplained default adapter

<s>What I can't figure out is why HTTPI.adapter is getting set to :net_http in my code.  AFAIK, I'm leaving it alone to let it set the default adapter.  All I know is that by the time this error occurs, the HTTPI.adapter has been set to :net_http by something.  We also use RestClient, although that doesn't directly invoke HTTPI, I wonder if HTTPI somehow detects other requires in use and sets the adapter based on what may already be loaded.</s>

Turns out that without explicitly using gem 'httpclient', HTTPI defaults to net_http in most cases.  Again, this doesn't cause an issue as long as Mechanize hasn't been loaded, invoking ntlm-http.  See [my second comment](https://github.com/savonrb/savon/issues/819#issuecomment-318076908) below.

## reproduction steps

Here is [a commit](https://github.com/coldnebo/savon/commit/75a4e7fb4ad10d4b9f2d8222ea435592a51cb03e) on my fork showing how to reproduce the issue.

Here is an example run:
```
$ rspec spec/integration/ntlm_example_spec.rb 
.F

Failures:

  1) rubyntlm side-effects should work with the net_http adapter as well
     Failure/Error: ops = client.operations
     ArgumentError:
       Invalid version of rubyntlm. Please use v0.3.2+.
     # ./lib/savon/client.rb:28:in `operations'
     # ./spec/integration/ntlm_example_spec.rb:51:in `block (2 levels) in <top (required)>'

Finished in 0.21419 seconds
2 examples, 1 failure

Failed examples:

rspec ./spec/integration/ntlm_example_spec.rb:41 # rubyntlm side-effects should work with the net_http adapter as well

Randomized with seed 34925

[Coveralls] Outside the CI environment, not sending data.
```

**Comment by coldnebo** [comment]
Removing httpclient from the Gemfile and testing harness in Savon results in a default of HTTPI to net_http.  [My second commit](https://github.com/coldnebo/savon/commit/094f8560f632e1fa1ed90755397805d9f5f30be5) shows that both soap calls fail without modifying the default HTTPI.adapter.

```
$ rspec spec/integration/ntlm_example_spec.rb
FF

Failures:

  1) rubyntlm side-effects works with the default adapter
     Failure/Error: ops = client.operations
     ArgumentError:
       Invalid version of rubyntlm. Please use v0.3.2+.
     # ./lib/savon/client.rb:28:in `operations'
     # ./spec/integration/ntlm_example_spec.rb:35:in `block (2 levels) in <top (required)>'

  2) rubyntlm side-effects should work with the net_http adapter as well
     Failure/Error: ops = client.operations
     ArgumentError:
       Invalid version of rubyntlm. Please use v0.3.2+.
     # ./lib/savon/client.rb:28:in `operations'
     # ./spec/integration/ntlm_example_spec.rb:56:in `block (2 levels) in <top (required)>'

Finished in 0.0137 seconds
2 examples, 2 failures

Failed examples:

rspec ./spec/integration/ntlm_example_spec.rb:25 # rubyntlm side-effects works with the default adapter
rspec ./spec/integration/ntlm_example_spec.rb:46 # rubyntlm side-effects should work with the net_http adapter as well

Randomized with seed 60445

[Coveralls] Outside the CI environment, not sending data.
```

**Comment by coldnebo** [comment]
Testing the new httpi version against my reproduction [commit](https://github.com/coldnebo/savon/commit/a84343c15e7b0ad61104db0f906523980991aee6) in savon:

```
$ rspec spec/integration/ntlm_example_spec.rb
..

Finished in 0.36559 seconds
2 examples, 0 failures

Randomized with seed 13646

[Coveralls] Outside the CI environment, not sending data.
```

**Comment by coldnebo** [comment]
Reran my reproduction steps after completing the httpi pull request:

```
$ rspec spec/integration/ntlm_example_spec.rb 
..

Finished in 0.4515 seconds
2 examples, 0 failures

Randomized with seed 58645

[Coveralls] Outside the CI environment, not sending data.
```

Confirmed. Final pull request still solves the problem.
