### ISSUE TITLE
NoMethodError (undefined method `read' for OpenSSL::PKey:Module)

### ISSUE THREAD

**Issue by Pecka40** [savonrb/savon#829]
I get this error `NoMethodError (undefined method `read' for OpenSSL::PKey:Module)` when trying to use SSL.

Ruby version 1.8.7 (2011-02-18 patchlevel 334) _Yes I know this is an old version. Its a very old project._
Here are my installed gems - 
`actionmailer (2.0.2)
actionpack (2.0.2)
activerecord (2.0.2)
activeresource (2.0.2)
activesupport (2.0.2)
akami (1.2.2)
builder (3.2.3)
bundler-unload (1.0.2)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
gyoku (1.3.1, 1.1.1)
handsoap (1.4.0)
httpclient (2.2.5)
httpi (2.4.2, 2.2.7)
macaddr (1.7.1)
mini_portile (0.6.2)
mini_portile2 (2.2.0)
mysql (2.9.1)
nokogiri (1.5.11, 1.5.10)
nori (2.6.0, 2.4.0)
pdfkit (0.8.2)
rack (2.0.3)
rails (2.0.2)
rake (10.0.0, 0.8.7)
ruby-mysql (2.9.14)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
savon (2.6.0)
socksify (1.7.1)
sqlite3 (1.3.13)
sqlite3-ruby (1.3.3)
systemu (2.6.5)
uuid (2.3.8)
wasabi (3.3.1)`

And this is the stack trace
`/home/dave/.rvm/gems/ruby-1.8.7-p334/gems/httpi-2.2.7/lib/httpi/auth/ssl.rb:97:in `cert_key'
/home/dave/.rvm/gems/ruby-1.8.7-p334/gems/httpi-2.2.7/lib/httpi/adapter/httpclient.rb:67:in `setup_ssl_auth'
/home/dave/.rvm/gems/ruby-1.8.7-p334/gems/httpi-2.2.7/lib/httpi/adapter/httpclient.rb:44:in `setup_client'
/home/dave/.rvm/gems/ruby-1.8.7-p334/gems/httpi-2.2.7/lib/httpi/adapter/httpclient.rb:25:in `request'
/home/dave/.rvm/gems/ruby-1.8.7-p334/gems/httpi-2.2.7/lib/httpi.rb:159:in `request'
/home/dave/.rvm/gems/ruby-1.8.7-p334/gems/httpi-2.2.7/lib/httpi.rb:131:in `post'
/home/dave/.rvm/gems/ruby-1.8.7-p334/gems/savon-2.6.0/lib/savon/operation.rb:86:in `call_with_logging'
/home/dave/.rvm/gems/ruby-1.8.7-p334/gems/savon-2.6.0/lib/savon/request_logger.rb:12:in `call'
/home/dave/.rvm/gems/ruby-1.8.7-p334/gems/savon-2.6.0/lib/savon/request_logger.rb:12:in `log'
/home/dave/.rvm/gems/ruby-1.8.7-p334/gems/savon-2.6.0/lib/savon/operation.rb:86:in `call_with_logging'
/home/dave/.rvm/gems/ruby-1.8.7-p334/gems/savon-2.6.0/lib/savon/operation.rb:51:in `call'
/home/dave/.rvm/gems/ruby-1.8.7-p334/gems/savon-2.6.0/lib/savon/client.rb:36:in `call'
app/models/vid_adfs_service.rb:26:in `login'`

Any help is much apreaciated!

**Comment by Pecka40** [comment]
If anyone has the same issue, leaving my answer here. 
I fixed it by downgrading to savon 2.3.0
