### ISSUE TITLE
Using different port than 80

### ISSUE THREAD

**Issue by mconiglio** [savonrb/savon#852]
Hello, I'm using version `2.11.1` of the gem. I'm having an issue when trying to call an operation using the client.

I get the wsdl using `https://someurl` and the client gets created correctly. The thing is that when trying to call an operation I get this error:
```
Errno::ECONNREFUSED: Connection refused - connect(2)
	from /Users/mauricioconiglio/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http.rb:878:in `initialize'
	from /Users/mauricioconiglio/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /Users/mauricioconiglio/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /Users/mauricioconiglio/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	from /Users/mauricioconiglio/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /Users/mauricioconiglio/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /Users/mauricioconiglio/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /Users/mauricioconiglio/.rvm/gems/ruby-2.0.0-p648/gems/httpi-2.4.1/lib/httpi/adapter/net_http.rb:76:in `do_request'
	from /Users/mauricioconiglio/.rvm/gems/ruby-2.0.0-p648/gems/httpi-2.4.1/lib/httpi/adapter/net_http.rb:33:in `request'
	from /Users/mauricioconiglio/.rvm/gems/ruby-2.0.0-p648/gems/httpi-2.4.1/lib/httpi.rb:161:in `request'
	from /Users/mauricioconiglio/.rvm/gems/ruby-2.0.0-p648/gems/httpi-2.4.1/lib/httpi.rb:133:in `post'
	from /Users/mauricioconiglio/.rvm/gems/ruby-2.0.0-p648/gems/savon-2.11.1/lib/savon/operation.rb:94:in `block in call_with_logging'
	from /Users/mauricioconiglio/.rvm/gems/ruby-2.0.0-p648/gems/savon-2.11.1/lib/savon/request_logger.rb:12:in `call'
	from /Users/mauricioconiglio/.rvm/gems/ruby-2.0.0-p648/gems/savon-2.11.1/lib/savon/request_logger.rb:12:in `log'
	from /Users/mauricioconiglio/.rvm/gems/ruby-2.0.0-p648/gems/savon-2.11.1/lib/savon/operation.rb:94:in `call_with_logging'
	from /Users/mauricioconiglio/.rvm/gems/ruby-2.0.0-p648/gems/savon-2.11.1/lib/savon/operation.rb:54:in `call'
	from /Users/mauricioconiglio/.rvm/gems/ruby-2.0.0-p648/gems/savon-2.11.1/lib/savon/client.rb:36:in `call'
```
I went down in the code and realized that the issue is when trying to open the tcp connection using something like `TCPSocket.open('someurl', 80)`.

What I found is that when trying to open the connection using the port 443 it works correctly. The problem is that I haven't found the way to do that from the Savon configuration. So what I would like to know is: how can I set that port number to be used when calling the operations?

Thanks.

**Comment by krutovgerman** [comment]
The same with the Version `2.12.1`.

The gem tries to call PORT 80 before a really CALL TO PORT 443.
