### ISSUE TITLE
Method call gives an error "HTTPClient::ConnectTimeoutError" with different adapters

### ISSUE THREAD

**Issue by YairFernando67** [savonrb/savon#939]
# Bug report

**Current behavior:**
I get an error when calling a method, I am not sure why I am getting this error but I think is related to the adapter that as far as I know httpclient is the default adapter. I have tried to set a different adapter like excon but I get the same error. I hope you can help me out.

I have also tried to add some attributes like, open_timeout: 100, read_timeout: 100, raise_errors: false, follow_redirects: true, host: "http://localhost:3000", but I still get the error.

I also tried with different versions of savon 2.11.1,  2.3.3, 2.12.0

**Steps to reproduce current behavior:**
```ruby
  WSDL_URL = 'http://www.webservicex.net/geoipservice.asmx?WSDL'
  @client = Savon.client(wsdl: WSDL_URL, adapter: :net_http)  # I have also tried with excon and httpclient
  response = @client.call(:query_tcrm)
```

This code gives me this error depending on the adapter.

> .rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/socksify-1.7.1/lib/socksify.rb:178:in `initialize': execution expired (HTTPClient::ConnectTimeoutError)

> .rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/excon-0.76.0/lib/excon/socket.rb:285:in `select_with_timeout': connect_write timeout reached (Excon::Error::Timeout)

> Net::OpenTimeout (execution expired):

**Expected behavior:**
The method call should be successful.

**System information:**

* ruby version: '2.6.4'
* savon version: '2.12.0'

**Comment by olleolleolle** [comment]
Here's a runnable example:

```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'wasabi', '= 3.5.0'
  gem 'savon'
end

WSDL_URL = 'https://www.superfinanciera.gov.co/SuperfinancieraWebServiceTRM/TCRMServicesWebService/TCRMServicesWebService?WSDL'
pp client = Savon.client(wsdl: WSDL_URL)  # I have also tried with excon and httpclient
pp client.operations
pp response = client.call(:query_tcrm)

pp response
```

Diagnostic question:
Can you use SmartBear's "SoapUI Open Source" to call this Web Service operation? https://www.soapui.org/downloads/soapui/

**Comment by YairFernando67** [comment]
I tried running the Web Service with Python and it worked. So I know the web service is working. I also used SoapUI Open Source.

So there is a problem with the Web Service or with the configurations on my side when using the gem?

**Comment by marcosdemelo** [comment]
@YairFernando67 Have you seen this below? Could you check if it solves your problem and report here? 

https://github.com/ruby/ruby/pull/597#issuecomment-40507119

**Comment by marcosdemelo** [comment]
Are you using the certificate that they recommend in the documentation?

Search it on Google: superfinanciera wsdl pdf

[20151228manualserviciowebtrm.pdf](https://github.com/savonrb/savon/files/5350687/20151228manualserviciowebtrm.pdf)

**Comment by YairFernando67** [comment]
@marcosdemelo yes I am using the certificate but I get the following errors.
```
  file = File.open('lib/cert.cer', "r")
  @client = Savon.client(wsdl: WSDL_URL, ssl_cert_file: file.read, ssl_cert_key_file: file.read, namespace_identifier: 'xw', 
  env_namespace: 'soap')
  response = @client.call(:query_tcrm)
  p response
rescue HTTPI::SSLError => e
  p e.message
```

> httpi-2.4.5/lib/httpi/auth/ssl.rb:128:in `read': File name too long @ rb_sysopen - -----BEG (Errno::ENAMETOOLONG)

And if I pass the certificate like this.
```
  @client = Savon.client(wsdl: WSDL_URL, ssl_cert_file: 'lib/cert.cer', ssl_cert_key_file: 'lib/cert.cer', namespace_identifier: 'xw', 
  env_namespace: 'soap')
  response = @client.call(:query_tcrm)
  p response
rescue HTTPI::SSLError => e
  p e.message
```

I get this other error.

> httpi-2.4.5/lib/httpi/auth/ssl.rb:144:in `read': Could not parse PKey: no start line (OpenSSL::PKey::PKeyError)

**Comment by clushie** [comment]
I'm also affected by this and couldn't find a way to make it working. Not using wsdl https://github.com/savonrb/savon/blob/master/lib/savon/request.rb#L9

**Comment by clushie** [comment]
I'm also affected by this and can't figure out a way to get https working.

My gut-feeling is that the `url` is passed at a later stage than the httpi request initialization when using wsdl which will HTTPI (or any other library) attempt to connect to a non ssl-host even though https is defined? But I might be completely wrong with that assumption.

This is where I'd expect to tell HTTPI to use ssl:

https://github.com/savonrb/savon/blob/d871e3b28a360e2f8a2526332f72029a10e541f0/lib/savon/request.rb#L9
